# Generated by Django 6.0.2 on 2026-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragrance',
            name='base_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fragrance',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fragrance',
            name='middle_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fragrance',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fragrance',
            name='top_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='applicable_size',
            field=models.CharField(blank=True, choices=[('30', '30 ML'), ('100', '100 ML')], max_length=3, null=True),
        ),
    ]
