# Generated by Django 6.0.2 on 2026-03-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_fragrance_base_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragrance',
            name='gender',
        ),
        migrations.AddField(
            model_name='fragrance',
            name='category',
            field=models.CharField(choices=[('him', 'For Him'), ('her', 'For Her'), ('unisex', 'Unisex'), ('oud', 'Oud')], default='him', max_length=10),
            preserve_default=False,
        ),
    ]
