# Generated by Django 6.0.2 on 2026-05-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_about_remove_sitesettings_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragrance',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
