# Generated by Django 6.0.2 on 2026-05-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_fragrance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_qr', models.ImageField(upload_to='payment/')),
                ('upi_id', models.CharField(default='yourupi@bank', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fragrance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
