# Generated by Django 6.0.2 on 2026-05-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_paymentqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
