# Generated by Django 6.0.2 on 2026-05-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_about_qr_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSettings',
        ),
        migrations.RemoveField(
            model_name='about',
            name='qr_code',
        ),
    ]
