# Generated by Django 6.0.2 on 2026-05-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_delete_paymentsettings_remove_about_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderimage',
            old_name='image',
            new_name='desktop_image',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/mobile/'),
        ),
    ]
